= Satanic Infestation

Satanic Infestation is my fork of Freedoom, because i disagree with the way it's going, the project seems to be trying to just make something that vaguely resembles Doom rather than a 100% free copy of it, all of the references to Satanism and Naziism have been scrubbed clean, the enemies bear only a slight resemblance to their Doom counterparts at best, and no resemblance at worst, and it generally doesn't capture the vibe of Doom well, my goal is to make a 100% free IWAD that is as close to Doom as i can legally make it, the enemies, weapons, textures, themes, and maps will all bear more of a resemblance to Doom, i'm only using Freedoom as a basis, as time goes on, i will replace more and more of Freedoom's assets with my own, and, eventually, all of the old assets will be replaced, anybody is free to contribute assets, but i plan for this to be more or less something of my own making, further detais on rules and other information about asset contributions can be found in CONTRIBUTIONS.adoc, credits go to the Freedoom contributors for making it easier for me to do this project by providing their assets, thank you to them, and thanks in advance to anybody who submits their work to this project
