= Satanic Infestation

Satanic Infestation is my fork of Freedoom, because i disagree with the way it's going, the project deems to be trying to just make something that vaguely resembles Doom rather than a 100% free copy of it, all of the references to Satanism and Naziism have been scrubbed clean, the enemies bear only a slight resemblance to their Doom counterparts at best, and no resemblance at worst, and it generally doesn't capture the vibe of Doom well, my goal is to make a 100% free IWAD that is as close to Doom as i can legally make it, the shit worms, shit bugs, and silly putties with guns will be replaced with enemies that more closely resemble their Doom counterparts, the levels will bear more of a likeness to the ones in Doom, and the motorized pizza cutter will be replaced with an actual chainsaw, i'm only using Freedoom as a basis, as time goes on, i will replace more and more of Freedoom's assets with my own, and, eventually, all of the old assets will be replaced, anybody is free to contribute assets, but i plan for this to be more or less something of my own making, all of my assets will be licensed under the Unlicense, the Freedoom assets, are, of course, licensed under the BSD license, i encourage all contributions to be licensed under the Unlicense as well, my rules for assets are to try to make them semi-close to their equivalents in Doom, for example, if you draw up a spritesheet for the Imp replacement that's a cow's head on a pair of robot legs, or something of that nature, it's not going to be accepted, but if it's a humanoid creature, it will almost certainly be accepted, all maps must be vanilla compatible, and use textures that can be found in the Doom or Doom 2 IWADs, when it comes to textures or flats, try to make it give off the same feel as the Doom textures, and if it has a pentagram in Doom, the new illustration must have a pentagram as well, credits go to the Freedoom contributors for making it easier for me to do this project by providing their assets, thank you to them, and thanks in advance to anybody who submits their work to this project
