= Satanic Infestation

Satanic Infestation is my fork of Freedoom, because i disagree with the way it’s going, the project seems to go in a lot of strange directions that don't go well with a Doom or Doom 2 IWAD replacement, all of the references to Satanism have been scrubbed clean, a lot of the new assets go in odd directions that don't go well with a Doom-esque atmosphere, and it generally doesn’t capture the vibe of Doom well.
 
My goal is to make a 100% free IWAD that is a better fit for what i think an open IWAD should be, the assets will all have a stronger Doom-esque spirit and vibe, i’m only using Freedoom as a basis, as time goes on, i will replace more and more of Freedoom’s assets with my own, and, eventually, all of the old assets will be replaced, anybody is free to contribute assets, but i plan for this to be more or less something of my own making, further details on rules and other information about asset contributions can be found below.
  ﻿
Credits go to the Freedoom contributors for making it easier for me to do this project by providing their assets, thank you to them, and thanks in advance to anybody who submits their work to this project
 
THIS PROJECT HAS NO AFFILIATIONS WITH OR ENDORSEMENTS BY THE DEVELOPERS OF DOOM, ID SOFTWARE, OR ZENIMAX MEDIA, ANY RESEMBLANCE IS PURELY COINCIDENTAL
