###############################################################################
# SubList.pm                                                                  #
# $Date: 12.02.14 $                                                           #
###############################################################################
# YaBB: Yet another Bulletin Board                                            #
# Open-Source Community Software for Webmasters                               #
# Version:        YaBB 2.6.11                                                 #
# Packaged:       December 2, 2014                                            #
# Distributed by: http://www.yabbforum.com                                    #
# =========================================================================== #
# Copyright (c) 2000-2014 YaBB (www.yabbforum.com) - All Rights Reserved.     #
# Software by:  The YaBB Development Team                                     #
#               with assistance from the YaBB community.                      #
###############################################################################
our $VERSION = '2.6.11';

$sublistpmver = 'YaBB 2.6.11 $Revision: 1611 $';
if ($action eq 'detailedversion') { return 1; }

%director = (
'activate' => 'Register.pm&user_activation',
'addbuddy' => 'Subs.pm&addBuddy',
'addfav' => 'Favorites.pm&AddFav',
'addtab2' => 'AdvancedTabs.pm&AddNewTab2',
'ajxmessage' => 'LivePreview.pm&DoLiveMessage',
'ajximmessage' => 'LivePreview.pm&DoLiveIM',
'ajxcal' => 'LivePreview.pm&DoLiveCal',
'bdrulecoll' => 'MessageIndex.pm&collapse_bdrule',
'boardnotify' => 'Notify.pm&BoardNotify',
'boardnotify2' => 'MyCenter.pm&mycenter',
'boardnotify3' => 'Notify.pm&BoardNotify2',
'checkboardpw' => 'Subs.pm&BoardPasswCheck',
'checkavail' => 'UserSelect.pm&checkUserAvail',
'collapse_all' => 'BoardIndex.pm&Collapse_All',
'collapse_cat' => 'BoardIndex.pm&Collapse_Cat',
'deletemultimessages' => 'MyCenter.pm&Del_Some_IM',
'deletetab' => 'AdvancedTabs.pm&DeleteTab',
'delpmfolder' => 'MyCenter.pm&AddFolder',
'dereferer' => 'Subs.pm&Dereferer',
'display' => 'Display.pm&Display',
'downloadfile' => 'Downloads.pm&DownloadFileCouter',
'edittab2' => 'AdvancedTabs.pm&EditTab2',
'eventcal' => 'EventCal.pm&eventcal',
'add_cal' => 'EventCal.pm&add_cal',
'del_cal' => 'EventCal.pm&del_cal',
'get_cal_ssi' => 'EventCalSSI.pm&get_cal_ssi',
'birthdaylist' => 'EventCalBirthdays.pm&birthdaylist',
'favorites' => 'MyCenter.pm&mycenter',
'findmember' => 'UserSelect.pm&FindMem',
'guestlang' => 'Subs.pm&setGuestLang',
'guestpm' => 'Post.pm&sendGuestPM',
'guestpm2' => 'Post.pm&sendGuestPM2',
'help' => 'HelpCentre.pm&GetHelpFiles',
'hide' => 'SetStatus.pm&SetStatus',
'im' => 'MyCenter.pm&mycenter',
'imcb' => 'MyCenter.pm&CallBack',
'imdraft' => 'MyCenter.pm&mycenter',
'imgroups' => 'MyCenter.pm&IMGroups',
'imlist' => 'UserSelect.pm&MemberList',
'imoutbox' => 'MyCenter.pm&mycenter',
'imprint' => 'Printpage.pm&Print_IM',
'imsend' => 'MyCenter.pm&mycenter',
'imsend2' => 'MyCenter.pm&mycenter',
'imshow' => 'MyCenter.pm&mycenter',
'imstorage' => 'MyCenter.pm&mycenter',
'imtostore' => 'MyCenter.pm&IMToStore',
'ipban_update' => 'Security.pm&ipban_update',
'iplookup' => 'IPLookup.pm&IPLookup',
'jump' => 'Subs.pm&dojump',
'lock' => 'SetStatus.pm&SetStatus',
'lockpoll' => 'Poll.pm&LockPoll',
'login' => 'LogInOut.pm&Login',
'login2' => 'LogInOut.pm&Login2',
'logout' => 'LogInOut.pm&Logout',
'markallasread' => 'BoardIndex.pm&MarkAllRead',
'markasread' => 'MessageIndex.pm&MarkRead',
'markims' => 'MyCenter.pm&MarkAll',
'markunread' => 'Display.pm&undumplog',
'memberpagedrop' => 'Subs.pm&MemberPageindex',
'memberpagetext' => 'Subs.pm&MemberPageindex',
'messageindex' => 'MessageIndex.pm&MessageIndex',
'messagepagedrop' => 'MessageIndex.pm&MessagePageindex',
'messagepagetext' => 'MessageIndex.pm&MessagePageindex',
'ml' => 'Memberlist.pm&Ml',
'modalert' => 'Post.pm&modAlert',
'modalert2' => 'Post.pm&modAlert2',
'modify' => 'ModifyMessage.pm&ModifyMessage',
'modify2' => 'ModifyMessage.pm&ModifyMessage2',
'modsearch' => 'AddModerators.pm&ModSearch',
'modsearch2' => 'AddModerators.pm&ModSearch2',
'multiadmin' => 'RemoveTopic.pm&Multi',
'multidel' => 'ModifyMessage.pm&MultiDel',
'multiremfav' => 'Favorites.pm&MultiRemFav',
'mycenter' => 'MyCenter.pm&mycenter',
'myprofile' => 'MyCenter.pm&mycenter',
'myprofile2' => 'MyCenter.pm&mycenter',
'myprofileAdmin' => 'MyCenter.pm&mycenter',
'myprofileAdmin2' => 'MyCenter.pm&mycenter',
'myprofileBuddy' => 'MyCenter.pm&mycenter',
'myprofileBuddy2' => 'MyCenter.pm&mycenter',
'myprofileContacts' => 'MyCenter.pm&mycenter',
'myprofileContacts2' => 'MyCenter.pm&mycenter',
'myprofileIM' => 'MyCenter.pm&mycenter',
'myprofileIM2' => 'MyCenter.pm&mycenter',
'myprofileOptions' => 'MyCenter.pm&mycenter',
'myprofileOptions2' => 'MyCenter.pm&mycenter',
'myusersrecentposts' => 'MyCenter.pm&mycenter',
'myviewprofile' => 'MyCenter.pm&mycenter',
'newpmfolder' => 'MyCenter.pm&AddFolder',
'next' => 'Display.pm&NextPrev',
'notify2' => 'Notify.pm&Notify2',
'notify3' => 'Notify.pm&Notify3',
'notify4' => 'MyCenter.pm&mycenter',
'pages' => 'MessageIndex.pm&ListPages',
'palette' => 'Palette.pm&ColorPicker',
'pmpagedrop' => 'MyCenter.pm&PmPageindex',
'pmpagetext' => 'MyCenter.pm&PmPageindex',
'pmsearch' => 'MyCenter.pm&mycenter',
'post' => 'Post.pm&Post',
'post2' => 'Post.pm&Post2',
'prev' => 'Display.pm&NextPrev',
'print' => 'Printpage.pm&Print',
'profile' => 'Profile.pm&ModifyProfile',
'profile2' => 'Profile.pm&ModifyProfile2',
'profileAdmin' => 'Profile.pm&ModifyProfileAdmin',
'profileAdmin2' => 'Profile.pm&ModifyProfileAdmin2',
'profileBuddy' => 'Profile.pm&ModifyProfileBuddy',
'profileBuddy2' => 'Profile.pm&ModifyProfileBuddy2',
'profileCheck' => 'Profile.pm&ProfileCheck',
'profileCheck2' => 'Profile.pm&ProfileCheck2',
'profileContacts' => 'Profile.pm&ModifyProfileContacts',
'profileContacts2' => 'Profile.pm&ModifyProfileContacts2',
'profileIM' => 'Profile.pm&ModifyProfileIM',
'profileIM2' => 'Profile.pm&ModifyProfileIM2',
'profileOptions' => 'Profile.pm&ModifyProfileOptions',
'profileOptions2' => 'Profile.pm&ModifyProfileOptions2',
'qsearch' => 'UserSelect.pm&quickSearch',
'qsearch2' => 'UserSelect.pm&doquicksearch',
'rearrsticky' => 'System.pm&Rearrange_Sticky',
'recent' => 'Recent.pm&RecentPosts',
'recenttopics' => 'Recent.pm&RecentTopics',
'register' => 'Register.pm&Register',
'register2' => 'Register.pm&Register2',
'remfav' => 'Favorites.pm&RemFav',
'reminder' => 'LogInOut.pm&Reminder',
'reminder2' => 'LogInOut.pm&Reminder2',
'removethread' => 'RemoveTopic.pm&DeleteThread',
'reordertab' => 'AdvancedTabs.pm&ReorderTab',
'resetpass' => 'LogInOut.pm&Reminder3',
'revalidatesession' => 'Sessions.pm&SessionReval',
'revalidatesession2' => 'Sessions.pm&SessionReval2',
'RSSboard' => 'RSS.pm&RSS_board',
'RSSrecent' => 'RSS.pm&RSS_recent',
'scpoll' => 'Poll.pm&ShowcasePoll',
'scpolldel' => 'Poll.pm&DelShowcasePoll',
'scpollcoll' => 'Poll.pm&collapse_poll',
'search' => 'Search.pm&plushSearch1',
'search2' => 'Search.pm&plushSearch2',
'sendtopic' => 'SendTopic.pm&SendTopic',
'sendtopic2' => 'SendTopic.pm&SendTopic2',
'setgtalk' => 'Display.pm&SetGtalk',
'showexternal' => 'BoardIndex.pm&RedirectExternalShow',
'shownotify' => 'MyCenter.pm&mycenter',
'showvoters' => 'Poll.pm&votedetails',
'smilieindex' => 'DoSmilies.pm&SmilieIndex',
'smilieput' => 'DoSmilies.pm&SmiliePut',
'split_splice' => 'MoveSplitSplice.pm&Split_Splice',
'sticky' => 'SetStatus.pm&SetStatus',
'threadpagedrop' => 'Display.pm&ThreadPageindex',
'threadpagetext' => 'Display.pm&ThreadPageindex',
'topicpreview' => 'MessageIndex.pm&SetTopicPreview',
'undovote' => 'Poll.pm&UndoVote',
'usersrecentposts' => 'Profile.pm&usersrecentposts',
'viewdownloads' => 'Downloads.pm&DownloadView',
'viewprofile' => 'Profile.pm&ViewProfile',
'vote' => 'Poll.pm&DoVote',
);

1;
